# Generated by Django 3.2.6 on 2021-10-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('STP', 'отправлен в обработку'), ('CNC', 'отменен'), ('PD', 'оплачен'), ('PRD', 'обрабатывается'), ('FM', 'формируется'), ('RDY', 'готов к выдаче')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
